service: serverless-typescript-demo

provider:
  name: aws
  runtime: nodejs4.3
  profile: TEKsystems
  region: us-west-2
  iamRoleStatements:
      - Effect: "Allow"
        Resource: "*"
        Action:
          - "kinesis:*"
  environment:
      KINESIS_STREAM: ${opt:stage, self:provider.stage}-data-receiver
      NODE_ENV: production
      basePath: dev/
  cfLogs: true

plugins:
  - serverless-webpack

functions:
  cars:
    handler: handler.cars
    events:
      - http:
         path: index
         method: get
         integration: lambda-proxy
